package com.groovify.jpa.model;

import jakarta.persistence.*;
import java.util.List;
import java.util.Objects;

/**
 * Entity representing a music genre.
 * <p>
 * Maps to the "Genre" table in the database. Each genre has a unique name
 * and can be associated with multiple clients (users) via a many-to-many relationship.
 */
@Entity
@Table(name = "Genre")
public class Genre {

    @Id
    @GeneratedValue
    @Column(name = "ID")
    private Long id;

    @Column(name = "Name", nullable = false, unique = true)
    private String name;

    /**
     * Many-to-many relationship to clients.
     * <p>
     * Each genre can be followed or preferred by multiple clients, and each client can
     * have multiple genres they enjoy. This mapping is bidirectional.
     */
    @ManyToMany(mappedBy = "genres")
    private List<Client> clients;

    /**
     * Default constructor required by JPA.
     * <p>
     * Creates an empty Genre instance with no initialized fields.
     */
    public Genre() {}

    /**
     * Constructs a Genre with the specified name.
     * <p>
     * The name uniquely identifies the genre in the system.
     *
     * @param name the name of the genre (e.g., Rock, Jazz, Pop)
     */
    public Genre(String name) {
        this.name = name;
    }

    // ------------------ Getters ------------------

    /**
     * Returns the unique identifier for this genre.
     * <p>
     * This ID is automatically generated by the database when the entity is persisted.
     *
     * @return the database-generated ID of the genre
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the name of the genre.
     * <p>
     * The name represents the music category (e.g., "Rock", "Hip-Hop", "Classical").
     *
     * @return the name of the genre
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the list of clients associated with this genre.
     * <p>
     * Each client in the list has expressed interest in or is linked to this genre.
     * May return {@code null} or an empty list if no clients are associated yet.
     *
     * @return a list of clients linked to this genre
     */
    public List<Client> getClient() {
        return clients;
    }

    // ------------------ Setters ------------------

    /**
     * Sets the unique identifier for this genre.
     * <p>
     * Typically managed by JPA and not set manually.
     *
     * @param id the database-generated ID to assign to this genre
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Sets the name of this genre.
     * <p>
     * The name should be unique and descriptive (e.g., "Electronic", "Blues").
     *
     * @param name the genre name to assign
     */
    public void setName(String name) {
        this.name = name;
    }

    // ------------------ Object Overrides ------------------

    /**
     * Compares this Genre to another object for equality.
     * <p>
     * Two genres are considered equal if they have the same name and associated clients.
     *
     * @param o the object to compare with
     * @return {@code true} if both objects represent the same genre; {@code false} otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Genre genre = (Genre) o;
        return Objects.equals(name, genre.name) && Objects.equals(clients, genre.clients);
    }

    /**
     * Returns a hash code for this genre.
     * <p>
     * The hash code is based on the genre's name and associated clients.
     *
     * @return an integer hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(name, clients);
    }
}
