package com.groovify.jpa.model;

import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a music playlist in the Groovify application.
 *
 * <p>This entity maps to the {@code Playlist} table in the database and stores
 * information such as the playlist name, description, associated client, and
 * the songs contained within it.</p>
 *
 * <p>Each playlist may contain multiple songs, and songs can belong to multiple playlists,
 * forming a many-to-many relationship managed through the {@code Playlist_Song} join table.</p>
 *
 * @author Nevin Fullerton
 * @version 1.0
 */
@Entity
@Table(name = "Playlist")
public class Playlist {

    /**
     * The unique identifier for the playlist.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue
    @Column(name = "ID")
    private Long id;

    /**
     * The display name of the playlist.
     */
    @Column(name = "Name")
    private String name;

    /**
     * A short textual description of the playlist’s theme, mood, or purpose.
     */
    @Column(name = "Description")
    private String description;

    /**
     * The ID of the client (user) who owns this playlist.
     * This acts as a foreign key reference to the {@code Client} entity.
     */
    @Column(name = "ClientID")
    private Long clientID;

    /**
     * The list of songs included in this playlist.
     * <p>Represents a many-to-many relationship with the {@link Song} entity,
     * joined through the {@code Playlist_Song} association table.</p>
     */
    @ManyToMany
    @JoinTable(
            name = "PlaylistSong",
            joinColumns = @JoinColumn(name = "PlaylistID"),
            inverseJoinColumns = @JoinColumn(name = "SongID")
    )
    private List<Song> songs;

    /**
     * Returns the list of songs in this playlist.
     *
     * @return a list of {@link Song} objects associated with this playlist
     */
    public List<Song> getSongs() {
        if (songs == null) {
            songs = new ArrayList<>();
            return songs;
        } else {
            return songs;
        }
    }

    /**
     * Sets the list of songs for this playlist.
     *
     * @param songs the list of {@link Song} objects to associate with this playlist
     */
    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }

    /**
     * Sets the unique identifier of the playlist.
     *
     * @param id the playlist ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the unique identifier of the playlist.
     *
     * @return the playlist ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the client ID associated with this playlist.
     *
     * @param id the client ID
     */
    public void setClientID(Long id) {
        this.clientID = id;
    }

    /**
     * Returns the client ID associated with this playlist.
     *
     * @return the client ID
     */
    public Long getClientID() {
        return clientID;
    }

    /**
     * Sets the name of the playlist.
     *
     * @param name the playlist name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the name of the playlist.
     *
     * @return the playlist name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets a description for the playlist.
     *
     * @param description a short description of the playlist
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the description of the playlist.
     *
     * @return the playlist description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Compares this Playlist to another object for equality.
     * <p>
     * Two Playlists are considered equal if they have the same non-null database ID.
     *
     * @param o the object to compare with
     * @return {@code true} if both objects represent the same Song; {@code false} otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Playlist)) return false;
        return id != null && id.equals(((Playlist) o).id);
    }

    /**
     * Returns a constant hash code for this entity.
     * <p>
     * The hash code is based on a fixed constant for JPA entity identity.
     *
     * @return a constant integer hash code
     */
    @Override
    public int hashCode() {
        return 31;
    }


}
